// <auto-generated />
using Mentoring.WEB.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mentoring.WEB.API.DAL.Migrations
{
    [DbContext(typeof(UnitedAppContext))]
    [Migration("20210418161428_DataSeedUniversitiesAndSpecialities")]
    partial class DataSeedUniversitiesAndSpecialities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mentoring.WEB.API.DAL.Entities.Speciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Національна безпека"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Право"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "дизайн"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Соціологія"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Фінанси, банківська справа та страхування"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Менеджмент"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Маркетинг"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "фінанси і кредит"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "менеджмент організацій і адміністрування"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "менеджмент зовнішньоекономічної діяльності"
                        });
                });

            modelBuilder.Entity("Mentoring.WEB.API.DAL.Entities.University", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Академія зовнішньої розвідки України",
                            ShortName = "AЗРУ"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Академія праці, соціальних відносин і туризму",
                            ShortName = "АПСВТ"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Вищий навчальний заклад \"Київська Академія перукарського мистецтва\"",
                            ShortName = "ВНЗ \"КАПМ\""
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Вищий навчальний заклад \"Київський економічний інститут менеджменту\" у формі Товариства з обмеженою відповідальністю",
                            ShortName = "КЕІМ"
                        });
                });

            modelBuilder.Entity("SpecialityUniversity", b =>
                {
                    b.Property<long>("SpecialitiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UniversitiesId")
                        .HasColumnType("bigint");

                    b.HasKey("SpecialitiesId", "UniversitiesId");

                    b.HasIndex("UniversitiesId");

                    b.ToTable("SpecialityUniversity");

                    b.HasData(
                        new
                        {
                            SpecialitiesId = 1L,
                            UniversitiesId = 1L
                        },
                        new
                        {
                            SpecialitiesId = 2L,
                            UniversitiesId = 2L
                        },
                        new
                        {
                            SpecialitiesId = 3L,
                            UniversitiesId = 2L
                        },
                        new
                        {
                            SpecialitiesId = 6L,
                            UniversitiesId = 2L
                        },
                        new
                        {
                            SpecialitiesId = 5L,
                            UniversitiesId = 4L
                        },
                        new
                        {
                            SpecialitiesId = 6L,
                            UniversitiesId = 4L
                        },
                        new
                        {
                            SpecialitiesId = 7L,
                            UniversitiesId = 4L
                        },
                        new
                        {
                            SpecialitiesId = 8L,
                            UniversitiesId = 4L
                        },
                        new
                        {
                            SpecialitiesId = 9L,
                            UniversitiesId = 4L
                        },
                        new
                        {
                            SpecialitiesId = 10L,
                            UniversitiesId = 4L
                        });
                });

            modelBuilder.Entity("SpecialityUniversity", b =>
                {
                    b.HasOne("Mentoring.WEB.API.DAL.Entities.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentoring.WEB.API.DAL.Entities.University", null)
                        .WithMany()
                        .HasForeignKey("UniversitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
